# Generated by Django 3.0.7 on 2020-06-26 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_boast', models.BooleanField(default=True)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
